name: Build & Deploy

on:
  push:
    branches:
      - live

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: sveltekit

      - name: Build
        run: npm run build

      - name: Upload Build
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-github-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-github-pages
        uses: actions/deploy-pages@v2
